language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
addons:
  postgresql: "9.4"
env:
  - "HARNESS_OPTIONS=j9 TEST_POD=1 TEST_ONLINE=postgresql://postgres@/minion_test"
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
install:
  - "cpanm -n Mojo::Pg Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
before_script:
  - psql -c 'create database minion_test;' -U postgres
sudo: required
notifications:
  email: false
